### ISSUE TITLE
assertj-db SoftAssertion doesnt work with assertj-core 3.19.0

### ISSUE THREAD

**Issue by willyhalim** [assertj/assertj-db#126]
This was ok if i use assertj-core 3.15.0 SoftAssertions , but it breaks in assertj-core 3.19.0 .
Its due to generic return type

```
 public RequestAssert assertThat(Request actual) {
        return proxy(RequestAssert.class, Request.class, actual);
    }
```

**Comment by VanRoy** [comment]
@willyhalim Can you tell me wich version of assertj-db do you use ?

**Comment by willyhalim** [comment]
Hi , I use assertj db version 2.0.2 , Thanks

**Comment by VanRoy** [comment]
@willyhalim Thanks for the information, can you provide a little snippet of code that permit me to reproduce the issue ?

**Comment by willyhalim** [comment]
Apologies for the delay

This works with assertj 3.14.0 and assertj db 2.0.2
```
public class DBAssertions extends SoftAssertions {
    public RequestAssert assertThat(Request actual) {
        return proxy(RequestAssert.class, Request.class, actual);
    }
}
```

But will have compilation error in assertj 3.19.0 ( due to generic return type is changed )
